name: 'deploy'

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    steps:
    
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, workflow file name or ID
        # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
        workflow: push_on_main.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        # Use the empty string ("") to ignore status or conclusion in the search
        workflow_conclusion: success

        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them into respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        # is treated as a regular expression if input name_is_regexp is true
        # will download only those artifacts with a name that matches this regular expression
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions
#         name: 'package'
        # Optional, search for the last workflow run whose stored an artifact named as in `name` input
        # default false
        search_artifacts: true
    
    
    - name: Azure Static Web Apps Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        # Action to perform
        action: 'upload'
        # Directory location of the application source code
        app_location: ${{github.workspace}}
        # Required token
        azure_static_web_apps_api_token: b9a4f8911241628f74af8b44c72c0a74be1a7c2b629a8d1574f992b2e8828a752-6be5d1de-cda1-47db-a8f5-419c936a7727003206794
        # Skips the build step for the application source code if set to true.
        skip_app_build: true
        
  deploy-qa:
      runs-on: ubuntu-latest
      name: Deploy to qa
      steps:

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: 'package'
          # Destination path
          path: ${{github.workspace}}

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: 'upload'
          # Directory location of the application source code
          app_location: ${{github.workspace}}
          # Required token
          azure_static_web_apps_api_token: 4802f137ba53fd2b990ea40259c5dc34c06ec70664a01d4bdbf9312434ea46fd2-12d598f4-56a6-4313-8464-99e9ed25d872003219110
          # Skips the build step for the application source code if set to true.
          skip_app_build: true


