name: 'deploy'

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Artifact name
        name: artifact
        # Destination path
        path: ${{github.workspace}}
    
    - name: Azure Static Web Apps Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        # Action to perform
        action: 'upload'
        # Directory location of the application source code
        app_location: ${{github.workspace}}
        # Required token
        azure_static_web_apps_api_token: 
        # Skips the build step for the application source code if set to true.
        skip_app_build: true
        
  deploy-qa:
      runs-on: ubuntu-latest
      name: Deploy to qa
      steps:

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: artifact
          # Destination path
          path: ${{github.workspace}}

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: 'upload'
          # Directory location of the application source code
          app_location: ${{github.workspace}}
          # Required token
          azure_static_web_apps_api_token: 
          # Skips the build step for the application source code if set to true.
          skip_app_build: true


