name: 'on pull request'

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: pnpm install, build
        run: |
          pnpm install
          pnpm build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test
        run: |
          pnpm type-check
          pnpm lint
          pnpm test
    
