name: 'commit on main'

on:
  push:
    branches:
      - 'main'
#     paths-ignore:
#       - README.md
#       - CONTRIBUTING.md
#   pull_request:
#     branches:
#       - '**'
jobs:
  before_script:
    runs-on: ubuntu-latest
    steps:
      - name: before script
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
          pnpm config set store-dir .pnpm-store
  build:
    runs-on: ubuntu-latest
    name: Build the package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: pnpm install, build
        run: |
          pnpm install
          pnpm build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
#           name: dist-without-markdown
          path: |
            dist

      
