name: 'commit on main'

on:
  push:
    branches:
      - 'main'
jobs:
  before_script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: V6.16
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 19.5

  build:
    runs-on: ubuntu-latest
    name: Build the package
    steps:
      
      - name: pnpm install, build
        run: |
          pnpm install
          pnpm build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist

      
